// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc_Q267-TgzpVa2UEE8pdzbsSSlRMTZN8',
    appId: '1:531140543329:web:d0639ac6ede89fc02c7b20',
    messagingSenderId: '531140543329',
    projectId: 'fullstack-social-media-fc9d7',
    authDomain: 'fullstack-social-media-fc9d7.firebaseapp.com',
    storageBucket: 'fullstack-social-media-fc9d7.firebasestorage.app',
    measurementId: 'G-25F0S2QYLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTyotUx76An5YR2OG6EpcIcqDfy2loaN4',
    appId: '1:531140543329:android:e48b91d45b48d71c2c7b20',
    messagingSenderId: '531140543329',
    projectId: 'fullstack-social-media-fc9d7',
    storageBucket: 'fullstack-social-media-fc9d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjShSVki21uT_Zd9Ru7Jessjl0e7EcGY',
    appId: '1:531140543329:ios:31dec66e31f8093f2c7b20',
    messagingSenderId: '531140543329',
    projectId: 'fullstack-social-media-fc9d7',
    storageBucket: 'fullstack-social-media-fc9d7.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaFullstack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjShSVki21uT_Zd9Ru7Jessjl0e7EcGY',
    appId: '1:531140543329:ios:31dec66e31f8093f2c7b20',
    messagingSenderId: '531140543329',
    projectId: 'fullstack-social-media-fc9d7',
    storageBucket: 'fullstack-social-media-fc9d7.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaFullstack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc_Q267-TgzpVa2UEE8pdzbsSSlRMTZN8',
    appId: '1:531140543329:web:d731439335f62f2b2c7b20',
    messagingSenderId: '531140543329',
    projectId: 'fullstack-social-media-fc9d7',
    authDomain: 'fullstack-social-media-fc9d7.firebaseapp.com',
    storageBucket: 'fullstack-social-media-fc9d7.firebasestorage.app',
    measurementId: 'G-1M4PVP50TN',
  );
}
